# Generated by Django 3.2.6 on 2021-08-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vwDrugTargets',
            fields=[
                ('hgnc_id', models.TextField(db_column='HGNC_ID', primary_key=True, serialize=False)),
                ('uniprot_id', models.TextField(db_column='Uniprot_ID')),
                ('drugbank_id', models.TextField(db_column='Drugbank_ID')),
                ('drug_name', models.TextField(db_column='Drug_name')),
                ('source', models.TextField(db_column='Source')),
                ('approved_symbol', models.TextField(db_column='Approved_symbol')),
                ('approved_name', models.TextField(db_column='Approved_name')),
                ('chromosome', models.TextField(db_column='Chromosome')),
            ],
            options={
                'db_table': 'vw_DrugTargets',
                'managed': False,
            },
        ),
    ]
